name: Angular CI/CD
on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test-e2e
      - name: Create an Azure DevOps Bug Workitem when a tests fails
        uses: stefanstranger/azuredevops-bug-action@1.1
        if: failure()
        with:
          OrganizationName: "metodyki-wytwarzania-oprogramowania"
          PAT: "PAT"
          ProjectName: "Azure Pipelines"
          AreaPath: "Azure Pipelines"
          IterationPath: "Azure Pipelines"
          GithubToken: "GithubToken"
          WorkflowFileName: "main.yml"
        env:
          PAT: ${{ secrets.PAT }}
          GithubToken: ${{ secrets.githubtoken }}
