name: Angular CI/CD
on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test-e2e
